version: '2.3'

services:

  rabbitmq:
    image: rabbitmq:3-management
    restart: always
    ports:
      - "15672:15672"

  campaign-service:
    build: campaign-service
    restart: on-failure
    ports:
      - "8081:8081"

  fan-service:
    build: fan-service
    restart: on-failure
    ports:
      - "8082:8082"

